export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const CHANGE_ACTIVITY = 'CHANGE_ACTIVITY';
export const CHANGE_EDITING_STATUS = 'CHANGE_EDITING_STATUS';
export const ON_SUBMIT_EDIT_INPUT = 'ON_SUBMIT_EDIT_INPUT';
export const CHANGE_DATA_BUTTON_ACTIVITY = 'CHANGE_DATA_BUTTON_ACTIVITY';
export const DELETE_UNACTIVE = 'DELETE_UNACTIVE';
export const REMOVE_LIST = 'REMOVE_LIST';
